### ISSUE TITLE
convert to API server

### ISSUE THREAD

**Issue by dbuentello** [NodejsHouston/sidenote-server#3]
If the goal is to make this a pure REST/Websocket API then it makes sense to remove swig dependency (and related code). Maybe optimize code to help route development (json responses, standardized HTTP status codes, etc...)

**Comment by juxta52** [comment]
True, likely will not need a templating engine.

**Comment by NPrescott** [comment]
I'd like input from someone more familiar with Hapi - but I think as far as standardizing HTTP responses we might move some of the [explicit calls to status codes](https://github.com/NodejsHouston/sidenote-server/blob/master/server/base/messages/index.js#L36) with Boom calls. Maybe @poeticninja could chime in on the idiomatic way to handle this?

The existing endpoints are currently serving JSON responses (for mock data)

**Comment by juxta52** [comment]
+1 I agree to utilizing Boom for error handling in your API.  

I also give a strong +1 on a standard / general signature of return responses (error or success) from an API engine.  The signature should be consistent and similar but might vary slightly between the different type of http method (GET, POST, PUT, DELETE).  Although the general signature might not suit every API need (forever and always), its a good practice to have one agreed upon format.

**Comment by poeticninja** [comment]
Boom is great because it provides constancy with the error message that the server will give. It is something easy to add as well. Another thing I would use is Joi for validation on the POST route. Any data coming into a server should pass a check to make sure it is what you need. This helps prevents server manipulation and server take downs.

**Comment by NPrescott** [comment]
Closing this as the issues have been either addressed (#5) or better defined (#10)
